version: '3.3'
services:
  postgres-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: dia-fin-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

volumes:
  postgres-db-data:
